### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/py-composite-action-lib#3]
```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/py-composite-action-lib/issues/1
- [ ] https://github.com/AbsaOSS/py-composite-action-lib/issues/4
- [ ] https://github.com/AbsaOSS/py-composite-action-lib/issues/6
- [ ] Integrate code from Living Documentation Generator action
- [ ] Release 0.1.0
```

**Comment by miroslavpojer** [comment]
Development of the library has been ended.
